---
env:
  global:
    - CC_TEST_REPORTER_ID = 0bcb4ff8ab69e0f75dedc78db9db09795b167d3a0a97a99a76d7102be63ade90
    - CODECOV_TOKEN = eac83efd-1c35-4c99-9416-831d177e4d88
language: ruby
cache: bundler
rvm:
  - 2.7.2
before_install: gem install bundler -v 2.1.4
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
# env:
#   - CODECOV_TOKEN = eac83efd-1c35-4c99-9416-831d177e4d88
after_success:
  - bash <(curl -s https://codecov.io/bash)
